
package com.form.admission;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author  Johnpaul
 */
public final class AdmissionForTheYear extends JFrame {
   
    /** Creates new form AdmissionForTheYear */
    public AdmissionForTheYear() {
        initComponents();
        try{
            update();
            
        }catch(IOException ioe){}
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pan1 = new javax.swing.JPanel();
        comb1 = new javax.swing.JComboBox();
        comb2 = new javax.swing.JComboBox();
        txt1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        but1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        pan1.setBackground(new java.awt.Color(255, 255, 255));
        pan1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADMISSIONS  FOR THE YEAR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 51, 204)));
        pan1.setToolTipText("JOHNPAUL");
        comb1.setForeground(new java.awt.Color(0, 51, 153));
        comb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select one", "Art", "Law", "Biological Science", "Physical Science","Engineering", "Environmental Science", "Medical Science", "Social Science","Humanities" }));
        comb1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "School:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        comb2.setForeground(new java.awt.Color(0, 51, 153));
        comb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select one","Communication art","International Law", "Aeronautics-Astronautics", "Applied Physics", "Architecture", "Biochemistry", "Micro Biology", "Computer Engineering", "Data science","Theology", "Geology", "Journalism", "Civil Law", "Nursing", "Philosophy" }));
        comb2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Program:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt1.setForeground(new java.awt.Color(0, 0, 153));
        txt1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Number 0f Students:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 12)));

        jScrollPane1.setName("");
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Applicant No.", "Roll No.", "Name", "Address", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        table.setDragEnabled(true);
        table.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(table);

        but1.setBackground(new java.awt.Color(0, 51, 204));
        but1.setFont(new java.awt.Font("Tahoma", 1, 14));
        but1.setForeground(new java.awt.Color(255, 255, 255));
        but1.setText("OK");
        but1.addActionListener((java.awt.event.ActionEvent evt) -> {
            AdmissionForTheYear.this.actionPerformed(evt);
        });

        javax.swing.GroupLayout pan1Layout = new javax.swing.GroupLayout(pan1);
        pan1.setLayout(pan1Layout);
        pan1Layout.setHorizontalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan1Layout.createSequentialGroup()
                        .addComponent(comb1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                        .addComponent(comb2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan1Layout.createSequentialGroup()
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                        .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
                .addContainerGap())
        );
        pan1Layout.setVerticalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comb2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(comb1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
        Object obj = (Object)evt.getSource();
        
        if(obj == but1){
            
            FileInputStream fin = null;
            try {
                String lookup = String.valueOf(comb2.getSelectedItem());
                String sch  = String.valueOf(comb1.getSelectedItem());
                File file = new File("JohnpaulProject.txt");
                fin = new FileInputStream(file);
                String data ="";
                int c = -1;
                try {
                    while((c=fin.read())!=-1 ) {
                        char value = (char) c;
                        data += String.valueOf(value);
                        
                    }
                } catch (IOException ex) {
                    Logger.getLogger(AdmissionForTheYear.class.getName()).log(Level.SEVERE, null, ex);
                }
String[]records = data.split("\r\n");
                String searched = "";
                int rowcounter=0;
                int columncounter = 0;
                for (String record : records) {
                    if (record.contains(lookup) && record.contains(sch)) {
                        String[] trimmedRecords = record.split("\t");
                        table.setValueAt(trimmedRecords[0],rowcounter,0);
                        table.setValueAt( trimmedRecords[21],rowcounter,1);
                        table.setValueAt(trimmedRecords[3]+"  "+trimmedRecords[4]+"  "+trimmedRecords[5],rowcounter,2);
                        table.setValueAt(trimmedRecords[6],rowcounter,3);
                        table.setValueAt(trimmedRecords[28],rowcounter,4);
                        rowcounter++;
                        
                        //txt1.setText("\t" +String.valueOf( counter));
                    } else {
                        JOptionPane.showMessageDialog(null,"No candidate found");
                        return;
                    }
                }   if(obj==but2){
                    dispose();
                    new HomePage().setVisible(true);
                }
            } //GEN-LAST:event_actionPerformed
            catch (FileNotFoundException ex) {
                Logger.getLogger(AdmissionForTheYear.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    fin.close();
                } catch (IOException ex) {
                    Logger.getLogger(AdmissionForTheYear.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }
   
    public void update()throws IOException{
 BufferedReader br = new BufferedReader(new FileReader("file"));
 String num = "";
 int counter = 0;
 while((num = br.readLine())!=null)
 {
 counter++;
       }
//counter++;
    txt1.setText("\t" +counter);
    }    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new AdmissionForTheYear().setVisible(true);
        });
    }
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JComboBox comb1;
    private javax.swing.JComboBox comb2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pan1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
    
}
