
package com.form.admission;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author  JOHNPAUL
 */
public class HomePage extends JFrame {
    
    /** Creates new form HomePage */
    public HomePage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        but1 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        pword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KNOWLEDGE ONLINE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 51, 204)));
        jPanel1.setToolTipText("JOHNPAUL");
        but1.setBackground(new java.awt.Color(255, 255, 255));
        but1.setFont(new java.awt.Font("Tahoma", 1, 14));
        but1.setForeground(new java.awt.Color(153, 0, 0));
        but1.setIcon(new javax.swing.ImageIcon("images/EDU26.jpg"));
        but1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLICK TO REGISTER", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 204)));
        but1.addActionListener((java.awt.event.ActionEvent evt) -> {
            HomePage.this.actionPerformed(evt);
        });

        but2.setBackground(new java.awt.Color(255, 255, 255));
        but2.setFont(new java.awt.Font("Arial Black", 1, 14));
        but2.setForeground(new java.awt.Color(0, 51, 102));
        but2.setIcon(new javax.swing.ImageIcon("images/stock-vector-illustration-of-a-bachelor-award-costume-in-a-book-cover.jpg"));
        but2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLICK TO  VIEW REPORT ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 204)));
        but2.addActionListener((java.awt.event.ActionEvent evt) -> {
            HomePage.this.actionPerformed(evt);
        });

        pword.setForeground(new java.awt.Color(0, 51, 153));
        pword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter password to view report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(pword, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
Object ob = (Object)evt.getSource();

if(ob.equals(but1)){
    new  Register().setVisible(true);
} 

if(ob==but2)
{
    char[] input = pword.getPassword();
    if(isPasswordCorrect(input)){
       new AdmissionForTheYear().setVisible(true); 
    
      
   // return;
      Arrays.fill(input,'0');
      pword.selectAll();
     // resetFocus();

}
    else{
        JOptionPane.showMessageDialog(null,"Please enter a valid password to view report");
    }
 
}

    }//GEN-LAST:event_actionPerformed
      private static boolean isPasswordCorrect(char[] input){
        boolean isCorrect = true;
        char[] correctPassword={'k','n','o','w','l','e','d','g','e'};
        if(input.length!=correctPassword.length){
            isCorrect = false;
            
        }
else{
            isCorrect = Arrays.equals(input,correctPassword);
}
    Arrays.fill(correctPassword,'o');
    return isCorrect;
    
      
    }
      /**
       * To center the JFrame window
     * @param frame
     * @param width
     * @param height
       **/
      public static void centreWindow(JFrame frame, int width, int height) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);

        // calculate perfect center
        int perf_x = (int) x - width/2;
        int perf_y = (int) y - height/2;

        frame.setLocation(perf_x, perf_y);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new HomePage().setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pword;
    // End of variables declaration//GEN-END:variables
    
}
