
package com.form.admission;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  JOHNPAUL
 */
public class Qualification extends JFrame {
    
    /** Creates new form Qualification */
    public Qualification() {
        setTitle("KNOWLEDGE ONLINE");
        initComponents();
    
        try{
        pickValue();
        }catch(IOException e){}
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pan1 = new javax.swing.JPanel();
        txt2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarea = new javax.swing.JTextArea();
        but1 = new javax.swing.JButton();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        lab2 = new javax.swing.JLabel();
        comb2 = new javax.swing.JComboBox();
        comb3 = new javax.swing.JComboBox();
        comb4 = new javax.swing.JComboBox();
        lab3 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        lab4 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pan1.setBackground(new java.awt.Color(255, 255, 255));
        pan1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUALIFICATION    DETAILS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(0, 51, 204)));
        pan1.setToolTipText("JOHNPAUL");
        txt2.setForeground(new java.awt.Color(0, 51, 153));
        txt2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        tarea.setColumns(20);
        tarea.setFont(new java.awt.Font("Monospaced", 0, 14));
        tarea.setForeground(new java.awt.Color(0, 51, 153));
        tarea.setRows(5);
        tarea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details of Recent Honors and Awards:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jScrollPane1.setViewportView(tarea);

        but1.setBackground(new java.awt.Color(0, 51, 204));
        but1.setFont(new java.awt.Font("Tahoma", 1, 14));
        but1.setForeground(new java.awt.Color(255, 255, 255));
        but1.setText("SUBMIT");
        but1.addActionListener((java.awt.event.ActionEvent evt) -> {
            Qualification.this.actionPerformed(evt);
        });

        txt5.setForeground(new java.awt.Color(0, 51, 153));
        txt5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt6.setForeground(new java.awt.Color(0, 51, 153));
        txt6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txt4.setForeground(new java.awt.Color(0, 51, 153));
        txt4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "University", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt1.setForeground(new java.awt.Color(0, 51, 153));
        txt1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graduation Degree Program", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt3.setForeground(new java.awt.Color(0, 51, 153));
        txt3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "School", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        lab2.setBorder(javax.swing.BorderFactory.createTitledBorder("Test Date"));

        comb2.setForeground(new java.awt.Color(0, 51, 153));
        comb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select one", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comb2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Day", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        comb3.setForeground(new java.awt.Color(0, 51, 153));
        comb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select one", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        comb3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Month", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        comb4.setForeground(new java.awt.Color(0, 51, 153));
        comb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select one","2022","2021","2020","2019","2018","2017","2016", "2015","2014","2013","2012","2011","2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960" }));
        comb4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Year", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        lab3.setBorder(javax.swing.BorderFactory.createTitledBorder("TOEFL Score (If required):"));

        txt7.setForeground(new java.awt.Color(0, 51, 153));
        txt7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Score(%)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        lab4.setBorder(javax.swing.BorderFactory.createTitledBorder("Graduate Record Examination(GRE) Scores"));

        lab1.setForeground(new java.awt.Color(51, 0, 153));
        lab1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Roll No.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        javax.swing.GroupLayout pan1Layout = new javax.swing.GroupLayout(pan1);
        pan1.setLayout(pan1Layout);
        pan1Layout.setHorizontalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pan1Layout.createSequentialGroup()
                                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt6, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(txt5, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                            .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                        .addGap(0, 0, 0)
                        .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                            .addGroup(pan1Layout.createSequentialGroup()
                                .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comb2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comb3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comb4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(211, 211, 211))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan1Layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan1Layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pan1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt1, txt2, txt3, txt4});

        pan1Layout.setVerticalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt4)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan1Layout.createSequentialGroup()
                        .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt7)
                            .addComponent(comb3)
                            .addComponent(comb2)
                            .addComponent(comb4))))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );

        pan1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt1, txt2, txt3, txt4});

        getContentPane().add(pan1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed

JButton but = (JButton)evt.getSource(); 
if(but ==but1){
    
       
    
                        String rollNo = lab1.getText();
			String gdp = txt1.getText();
			String  grd = txt2.getText();
                        
			String sch = txt3.getText();
			String uni = txt4.getText();
                        String  gre = txt5.getText();
                        String  tofel = txt6.getText();
			 String score = txt7.getText();
                        String day = String.valueOf(comb2.getSelectedItem());
                        String mont = String.valueOf(comb3.getSelectedItem());
                        String yr = String.valueOf(comb4.getSelectedItem());
			String  drhw = tarea.getText();
                        
                        
                        if(gdp.length()==0)
			{
			JOptionPane.showMessageDialog(null,"please enter your graduation degree program");
                       
                        return;
                        }
                        
			
			if(grd.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your grade");
			return;
			}
                        
			if(sch.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your school name");
			return;
                        }
                         
			if(uni.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your university name");
			return;
                        }
                        if(grd.length()==0)
			{
			JOptionPane.showMessageDialog(null,"please enter your graduate record examination score");
                        return;
			}
    
			if(tofel.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your TOEFL score");
			return;
			}
                        
			if(day.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please select the day you wrote the test");
			return;
			}
			if(mont.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please select  the month you wrote the test");
			return;
			}
			if(yr.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please select the year you wrote the test");
			return;
			}
                        
			if(score.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your test score");
			return;
			}
                        /**
			if(drhw.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your recent honors and awards");
                        
			return;
			}
                         */
                        dispose();
                        JOptionPane.showMessageDialog(null,"Thanks for completing your registration successfully");
			
			try
				{
                            try (RandomAccessFile raf = new RandomAccessFile("JohnpaulProject.txt","rw")) {
                                raf.seek(raf.length());
                                
                                raf.writeBytes(rollNo+"\t"+grd+"\t"+sch+"\t"+uni+"\t"+gre+"\t"+tofel+"\t"+day+"\t"+mont+"\t"+yr+"\t"+score+"\t"+drhw+"\r\n");
                            }
                            
				}
				catch(IOException ioe)
				{
				System.out.println("Error:"+ioe.getMessage());
                                }
                        
           	        txt1.setText("");
			txt2.setText("");
			txt3.setText("");
			
			txt4.setText("");
			txt5.setText("");
			txt6.setText("");
                               
			txt7.setText("");
	
                        tarea.setText("");
    }//GEN-LAST:event_actionPerformed
    }
private void pickValue() throws IOException{
     
    File file = new File("JohnpaulProject.txt");
    FileInputStream fi = new FileInputStream(file);
    String data ="";
    int counter = 0;
    int c = -1;
    while((c=fi.read())!=-1 )
    {
    char value = (char) c;
    data += String.valueOf(value);

    }
    String[]records = data.split("\r\n");
    

        for (String record : records) {
            String[] trimmedRecords = record.split("\t");
            txt1.setText(""+trimmedRecords[1]);
            txt3.setText(""+trimmedRecords[2]);
            counter++;
            lab1.setText("Reg/0"+counter);
        }
      
      
}
     
                        
    /**
     * @param args the command line arguments
     */
  
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Qualification().setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but1;
    private javax.swing.JComboBox comb2;
    private javax.swing.JComboBox comb3;
    private javax.swing.JComboBox comb4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JPanel pan1;
    private javax.swing.JTextArea tarea;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    // End of variables declaration//GEN-END:variables
    
}
