
package com.form.admission;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.RandomAccessFile;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author  JOHNPAUL
 */
public class Register extends JFrame {


    /** Creates new form Register */
    public Register() {
        
        initComponents();
     try{
            generateAppNo();
        }catch(IOException ioe)
        {System.err.println(ioe.getMessage());  }
           
          
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pan1 = new javax.swing.JPanel();
        lab2 = new javax.swing.JLabel();
        comb1 = new javax.swing.JComboBox();
        comb2 = new javax.swing.JComboBox();
        lab3 = new javax.swing.JLabel();
        sep1 = new javax.swing.JSeparator();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        pan2 = new javax.swing.JPanel();
        comb3 = new javax.swing.JComboBox();
        comb4 = new javax.swing.JComboBox();
        comb5 = new javax.swing.JComboBox();
        txt4 = new javax.swing.JTextField();
        pan3 = new javax.swing.JPanel();
        txt12 = new javax.swing.JTextField();
        txt13 = new javax.swing.JTextField();
        txt14 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        comb6 = new javax.swing.JComboBox();
        comb7 = new javax.swing.JComboBox();
        but1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lab4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pan1.setBackground(new java.awt.Color(255, 255, 255));
        pan1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "KNOWLEDGE ONLINE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153)), "APPLICATION FORM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 1, 24), new java.awt.Color(0, 51, 204)));
        pan1.setToolTipText("JOHNPAUL");
        lab2.setFont(new java.awt.Font("Tahoma", 1, 12));
        lab2.setText("Applying for:");

        comb1.setForeground(new java.awt.Color(0, 51, 153));
        comb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One", "Aeronautics-Astronautics", "Applied Physics", "Architecture", "Biochemistry", "Business Education", "Civil Engineering", "Civil Law", "Economics", "Geology", "Journalism", "Nursing", "Philosophy" }));
        comb1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Graduate Degree Program:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        comb2.setForeground(new java.awt.Color(0, 51, 153));
        comb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One", "Art", "Biological  Science", "Earth Science", "Education", "Engineering", "Environmental Science", "Humanities", "Law", "Medical  Science", "Physical Science", "Social Science" }));
        comb2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "School:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        lab3.setFont(new java.awt.Font("Tahoma", 1, 12));
        lab3.setText("Personal Details:");

        txt1.setForeground(new java.awt.Color(0, 51, 153));
        txt1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt2.setForeground(new java.awt.Color(0, 51, 153));
        txt2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Middle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt3.setForeground(new java.awt.Color(0, 51, 153));
        txt3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        pan2.setBackground(new java.awt.Color(255, 255, 255));
        pan2.setBorder(javax.swing.BorderFactory.createTitledBorder("Date of Birth:"));
        comb3.setForeground(new java.awt.Color(0, 51, 153));
        comb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        comb3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Month", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        comb4.setForeground(new java.awt.Color(0, 51, 153));
        comb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comb4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Day", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        comb5.setForeground(new java.awt.Color(0, 51, 153));
        comb5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940" }));
        comb5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Year", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        javax.swing.GroupLayout pan2Layout = new javax.swing.GroupLayout(pan2);
        pan2.setLayout(pan2Layout);
        pan2Layout.setHorizontalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(comb3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(comb4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(comb5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pan2Layout.setVerticalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comb5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comb3, comb4, comb5});

        txt4.setForeground(new java.awt.Color(0, 51, 153));
        txt4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        pan3.setBackground(new java.awt.Color(255, 255, 255));
        pan3.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone Number"));
        txt12.setForeground(new java.awt.Color(0, 51, 153));
        txt12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Residence No.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt13.setForeground(new java.awt.Color(0, 51, 153));
        txt13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mobile No.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt14.setForeground(new java.awt.Color(0, 51, 153));
        txt14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Office No.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        javax.swing.GroupLayout pan3Layout = new javax.swing.GroupLayout(pan3);
        pan3.setLayout(pan3Layout);
        pan3Layout.setHorizontalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(txt13, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(txt14, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addContainerGap())
        );
        pan3Layout.setVerticalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan3Layout.createSequentialGroup()
                .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pan3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt12, txt13, txt14});

        txt5.setForeground(new java.awt.Color(0, 51, 153));
        txt5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "City", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt6.setForeground(new java.awt.Color(0, 51, 153));
        txt6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "State", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt7.setForeground(new java.awt.Color(0, 51, 153));
        txt7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Zip Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt8.setForeground(new java.awt.Color(0, 51, 153));
        txt8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Country", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt9.setForeground(new java.awt.Color(0, 51, 153));
        txt9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Country Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt10.setForeground(new java.awt.Color(0, 51, 153));
        txt10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Area Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txt11.setForeground(new java.awt.Color(0, 51, 153));
        txt11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        comb6.setForeground(new java.awt.Color(0, 51, 153));
        comb6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One", "Female", "Male" }));
        comb6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        comb7.setForeground(new java.awt.Color(0, 51, 153));
        comb7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select One", "U.S. Citizen", "U.S. Permanent Resident", "Not a U.S. Citizen", "Decline to State" }));
        comb7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Citizenship Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        but1.setBackground(new java.awt.Color(0, 0, 102));
        but1.setFont(new java.awt.Font("Arial Black", 1, 14));
        but1.setForeground(new java.awt.Color(255, 255, 255));
        but1.setText("CONTINUE");
        but1.addActionListener((java.awt.event.ActionEvent evt) -> {
            Register.this.actionPerformed(evt);
        });

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));

        lab4.setFont(new java.awt.Font("Arial Black", 1, 12));
        lab4.setForeground(new java.awt.Color(0, 51, 153));
        lab4.setBorder(javax.swing.BorderFactory.createTitledBorder("Form No."));

        javax.swing.GroupLayout pan1Layout = new javax.swing.GroupLayout(pan1);
        pan1.setLayout(pan1Layout);
        pan1Layout.setHorizontalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pan1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pan1Layout.createSequentialGroup()
                        .addComponent(comb1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(comb2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pan1Layout.createSequentialGroup()
                        .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sep1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addComponent(pan2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pan1Layout.createSequentialGroup()
                                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt8)
                                    .addComponent(txt5, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(txt6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt10)
                                    .addComponent(txt7, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan1Layout.createSequentialGroup()
                                .addComponent(comb6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(comb7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(txt11, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pan1Layout.createSequentialGroup()
                        .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE))
                    .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181))
            .addGroup(pan1Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(but1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pan1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comb1, comb2});

        pan1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt1, txt2, txt3});

        pan1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt10, txt5, txt6, txt7, txt8, txt9});

        pan1Layout.setVerticalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan1Layout.createSequentialGroup()
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lab2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comb1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pan3, 0, 179, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comb7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb6))
                .addGap(9, 9, 9)
                .addComponent(but1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pan1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comb1, comb2});

        pan1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt1, txt2, txt3});

        pan1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt10, txt11, txt4, txt5, txt6, txt7, txt8, txt9});

        pan1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comb6, comb7});

        getContentPane().add(pan1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
Object ob =(Object)evt.getSource();
			if(ob == but1)
			{ 
    
    //Random r = new Random();
    //Math.abs((r.nextInt())% 101);
                 	String gdp = String.valueOf(comb1.getSelectedItem());
                        String sch = String.valueOf(comb2.getSelectedItem());
                        String mont = String.valueOf(comb3.getSelectedItem());
                        String day = String.valueOf(comb4.getSelectedItem());
                        String yr = String.valueOf(comb5.getSelectedItem());
                        String genda = String.valueOf(comb6.getSelectedItem());
                        String citizn = String.valueOf(comb7.getSelectedItem());
			String fst = txt1.getText();
			String mid = txt2.getText();
			String last = txt3.getText();
			String add = txt4.getText();
			String cty = txt5.getText();
			String stat = txt6.getText();
			String zip = txt7.getText();
			String contry = txt8.getText();
			String concod = txt9.getText();
			String aracod = txt10.getText();
			String email = txt11.getText();
			String residentNo = txt12.getText();
			String mobileNo = txt13.getText();
			String officeNo = txt14.getText();
                        String AppNo  = lab4.getText(); 
		  	
                        
                     
                       
                        if(comb1.getSelectedIndex()== 0)
			{
			JOptionPane.showMessageDialog(null,"Please select  program of your choice");
                        return;
                        }
                        if(comb2.getSelectedIndex()== 0)
			{
			JOptionPane.showMessageDialog(null,"Please select one school");
                        return;
                        }
                        
			if(fst.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your first name");
                        return;
                        }
                        
			if(mid.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your middle name");
			return;
			}
			if(last.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your last name");
                        return;
                        }
                        if(comb3.getSelectedIndex() == 0)
			{
			JOptionPane.showMessageDialog(null,"please select your  month of birth");
			return;
			}
    
			if(comb4.getSelectedIndex() == 0)
			{
			JOptionPane.showMessageDialog(null,"please select your date of birth");
			return;
			}
			if(comb5.getSelectedIndex() == 0)
			{
			JOptionPane.showMessageDialog(null,"please select your year of birth");
                        
			return;
			}
                        if(add.length()==0)
			{
			JOptionPane.showMessageDialog(null,"please enter your address");
                        return;
			}
                        
			if(cty.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your city name");
			return;
			}
                        
			if(stat.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your state name");
                        return;
                        }
			if(zip.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your zip code");
                        return;
                        }
			if(contry.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your country name");
			return;
                        }
                        
			if(concod.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your country code");
			return;
			}
			if(aracod.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter your area code");
			return;
                        }
                        if(email.length()==0 || !email.contains("@"))
			{
			JOptionPane.showMessageDialog(null,"please enter a valid e-mail adress");
                        return;
			}
                        if(residentNo.length()==0 && officeNo.length() == 0 && mobileNo.length() == 0)
			{
			JOptionPane.showMessageDialog(null,"please enter atleast any of your residence , mobile or office number ");
                        
                        return;
                        }
			
                        
                        if(comb6.getSelectedIndex()== 0)
			{
			JOptionPane.showMessageDialog(null,"Please select your gender");
                        return;
                        }
                        if(comb7.getSelectedIndex()== 0)
			{
			JOptionPane.showMessageDialog(null,"Please select your citizenship status");
                        return;
                        }
                        
			try
				{
                             try (RandomAccessFile raf = new RandomAccessFile("JohnpaulProject.txt","rw")) {
                                 raf.seek(raf.length());
                                 raf.writeBytes(AppNo+" \t " +gdp+ " \t " +sch +" \t " +fst+" "+ mid+"  "+last+" \t "+add+" \t "+cty+" \t " +stat+" \t "+zip+" \t "+contry+" \t "+concod+" \t " +aracod+ "\t"+residentNo+" \t "+mobileNo+"\t"+officeNo+" \t "+email+" \t "+mont+" \t " +day+" \t "+yr + " \t ");
                                 //new Qualification(gdp +sch);
                             }
				}
				catch(IOException ioe)
				{
				JOptionPane.showMessageDialog(this,"Error:"+ioe.getMessage());
                                } 
                        
     
                        
                        
                        
                        comb1.setSelectedIndex(0);
                        comb2.setSelectedIndex(0);
                        comb3.setSelectedIndex(0);
                        comb4.setSelectedIndex(0);
                        comb5.setSelectedIndex(0);
                        comb6.setSelectedIndex(0);
                     
           	        txt1.setText("");
			txt2.setText("");
			txt3.setText("");
			
			txt4.setText("");
			txt5.setText("");
			txt6.setText("");
                               
			txt7.setText("");
			txt8.setText("");
			
			txt9.setText("");
			txt10.setText("");
			txt11.setText("");
		        txt12.setText("");
			
			txt13.setText("");
			
			txt14.setText("");
                     
                       
                       new Qualification().setVisible(true);
			dispose();
    
                        

                        }
    }//GEN-LAST:event_actionPerformed

    
                        private void generateAppNo()throws IOException
                        {
                         File file = new File("JohnpaulProject.txt");
                        BufferedReader br = new BufferedReader(new FileReader(file));
                        String data = "";
                        int counter = 0;
                       while((data = br.readLine())!=null){
                            counter++;
                       }
                        counter++;
                             lab4.setText("AP00"+counter);
                       
                        }

    /**
     *
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but1;
    private javax.swing.JComboBox comb1;
    private javax.swing.JComboBox comb2;
    private javax.swing.JComboBox comb3;
    private javax.swing.JComboBox comb4;
    private javax.swing.JComboBox comb5;
    private javax.swing.JComboBox comb6;
    private javax.swing.JComboBox comb7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JPanel pan3;
    private javax.swing.JSeparator sep1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
    
}
